version: '3.8'

services:
  mysql:
    image: tymoteuszbolalek/miniapibiblioteczne-mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: librarydb
      MYSQL_USER: libraryuser
      MYSQL_PASSWORD: 1234567812345678
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: tymoteuszbolalek/miniapibiblioteczne-app:latest
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/librarydb
      SPRING_DATASOURCE_USERNAME: libraryuser
      SPRING_DATASOURCE_PASSWORD: 1234567812345678
    ports:
      - "8081:8081"

volumes:
  mysql-data:
