spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:librarydb
    username: tymek
    password: brak
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true

jwt:
  secret: secret_key   # Sekret do podpisywania JWT
  expiration: 3600000  # Czas wa?no?ci tokenu w milisekundach (np. 1 godzina)
