spring:
  datasource:
    url: jdbc:mysql://mysql:3306/librarydb
    username: libraryuser
    password: 1234567812345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework: DEBUG
    security: DEBUG
    web: DEBUG

server:
  port: 8081
