spring:
  datasource:
    url: jdbc:mysql://localhost:3306/librarydb #spring
    username: libraryuser
    password: 1234567812345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://db:3306/librarydb DB_CLOSE_DELAY=-1 #docker


  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework:
    security: DEBUG
    web: DEBUG


server:
  port: 8081

