version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: librarydb
      MYSQL_USER: libraryuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - backend

  app:
    build: .
    container_name: mini-api
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/librarydb
      SPRING_DATASOURCE_USERNAME: libraryuser
      SPRING_DATASOURCE_PASSWORD: password

networks:
  backend:
